### PR TITLE
Update checkstyle to require indent to 4 spaces

### PR DESCRIPTION
**Pull request by kornys**
## Description

To unify code style require indent level to  spaces

## Type of Change

Please delete options that are not relevant.

* Checkstyle update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit/integration tests pass locally with my changes

### CODE REVIEW

**Comment by im-konge** [comment]
I never liked the 4 tabs indent, it seems a bit weird to me. Is that some standard that should be kept?
Also, why is the spaces in javadoc changed? Having a proper space between the "parameter name" and the description makes the text more readable.

**Comment by kornys** [comment]
> I never liked the 4 tabs indent, it seems a bit weird to me. Is that some standard that should be kept? Also, why is the spaces in javadoc changed? Having a proper space between the "parameter name" and the description makes the text more readable.

Well it is not a 4 tabs indent but 4 spaces which is one tab in IDEA for example....
Javadoc is changed because of idea auto-format when I applied changes

**Comment by im-konge** [comment]
As I said nothing. Yeah I have 4 everywhere.

> Javadoc is changed because of idea auto-format when I applied changes

So should it be changed back or should it be kept as it is? Just asking.

**Comment by kornys** [comment]
> As I said nothing. Yeah I have 4 everywhere.
> 
> > Javadoc is changed because of idea auto-format when I applied changes
> 
> So should it be changed back or should it be kept as it is? Just asking.

I can do it, later

**Review by im-konge — APPROVED** [review]

**Pull request merged**
